export const ERROR_HTTP_STATUS_CODES: Record<string, number> = {
  ALREADY_EXISTS: 409,
  CONFLICT: 409,
  INVALID_STATE_TRANSITION: 409,
  INVALID_CREDENTIALS: 401,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  PRECONDITION_FAILED: 412,
  SERVICE_UNAVAILABLE: 503,
  VALIDATION_ERROR: 400,
};
