/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedManufacturersIndexRouteImport } from './routes/_authenticated/manufacturers/index'
import { Route as AuthenticatedPatientsIndexRouteImport } from './routes/_authenticated/patients/index'
import { Route as AuthenticatedPatientsPatientIdRouteImport } from './routes/_authenticated/patients/$patientId'
import { Route as AuthenticatedProductsIndexRouteImport } from './routes/_authenticated/products/index'
import { Route as AuthenticatedQueuesIndexRouteImport } from './routes/_authenticated/queues/index'
import { Route as AuthenticatedRolesIndexRouteImport } from './routes/_authenticated/roles/index'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedPatientsPatientIdIndexRouteImport } from './routes/_authenticated/patients/$patientId/index'
import { Route as AuthenticatedReferencesConditionsIndexRouteImport } from './routes/_authenticated/references/conditions/index'
import { Route as AuthenticatedReferencesProceduresIndexRouteImport } from './routes/_authenticated/references/procedures/index'
import { Route as AuthenticatedPatientsPatientIdVisitsIndexRouteImport } from './routes/_authenticated/patients/$patientId/visits/index'
import { Route as AuthenticatedPatientsPatientIdVisitsVisitIdRouteImport } from './routes/_authenticated/patients/$patientId/visits/$visitId'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedManufacturersIndexRoute =
  AuthenticatedManufacturersIndexRouteImport.update({
    id: '/manufacturers/',
    path: '/manufacturers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsIndexRoute =
  AuthenticatedPatientsIndexRouteImport.update({
    id: '/patients/',
    path: '/patients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdRoute =
  AuthenticatedPatientsPatientIdRouteImport.update({
    id: '/patients/$patientId',
    path: '/patients/$patientId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProductsIndexRoute =
  AuthenticatedProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedQueuesIndexRoute =
  AuthenticatedQueuesIndexRouteImport.update({
    id: '/queues/',
    path: '/queues/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRolesIndexRoute = AuthenticatedRolesIndexRouteImport.update({
  id: '/roles/',
  path: '/roles/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPatientsPatientIdIndexRoute =
  AuthenticatedPatientsPatientIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedReferencesConditionsIndexRoute =
  AuthenticatedReferencesConditionsIndexRouteImport.update({
    id: '/references/conditions/',
    path: '/references/conditions/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedReferencesProceduresIndexRoute =
  AuthenticatedReferencesProceduresIndexRouteImport.update({
    id: '/references/procedures/',
    path: '/references/procedures/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPatientsPatientIdVisitsIndexRoute =
  AuthenticatedPatientsPatientIdVisitsIndexRouteImport.update({
    id: '/visits/',
    path: '/visits/',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)
const AuthenticatedPatientsPatientIdVisitsVisitIdRoute =
  AuthenticatedPatientsPatientIdVisitsVisitIdRouteImport.update({
    id: '/visits/$visitId',
    path: '/visits/$visitId',
    getParentRoute: () => AuthenticatedPatientsPatientIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/patients/': typeof AuthenticatedPatientsIndexRoute
  '/products/': typeof AuthenticatedProductsIndexRoute
  '/queues/': typeof AuthenticatedQueuesIndexRoute
  '/roles/': typeof AuthenticatedRolesIndexRoute
  '/users/': typeof AuthenticatedUsersIndexRoute
  '/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/references/conditions/': typeof AuthenticatedReferencesConditionsIndexRoute
  '/references/procedures/': typeof AuthenticatedReferencesProceduresIndexRoute
  '/patients/$patientId/visits/$visitId': typeof AuthenticatedPatientsPatientIdVisitsVisitIdRoute
  '/patients/$patientId/visits/': typeof AuthenticatedPatientsPatientIdVisitsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AuthenticatedIndexRoute
  '/manufacturers': typeof AuthenticatedManufacturersIndexRoute
  '/patients': typeof AuthenticatedPatientsIndexRoute
  '/products': typeof AuthenticatedProductsIndexRoute
  '/queues': typeof AuthenticatedQueuesIndexRoute
  '/roles': typeof AuthenticatedRolesIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/patients/$patientId': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/references/conditions': typeof AuthenticatedReferencesConditionsIndexRoute
  '/references/procedures': typeof AuthenticatedReferencesProceduresIndexRoute
  '/patients/$patientId/visits/$visitId': typeof AuthenticatedPatientsPatientIdVisitsVisitIdRoute
  '/patients/$patientId/visits': typeof AuthenticatedPatientsPatientIdVisitsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/patients/$patientId': typeof AuthenticatedPatientsPatientIdRouteWithChildren
  '/_authenticated/manufacturers/': typeof AuthenticatedManufacturersIndexRoute
  '/_authenticated/patients/': typeof AuthenticatedPatientsIndexRoute
  '/_authenticated/products/': typeof AuthenticatedProductsIndexRoute
  '/_authenticated/queues/': typeof AuthenticatedQueuesIndexRoute
  '/_authenticated/roles/': typeof AuthenticatedRolesIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/patients/$patientId/': typeof AuthenticatedPatientsPatientIdIndexRoute
  '/_authenticated/references/conditions/': typeof AuthenticatedReferencesConditionsIndexRoute
  '/_authenticated/references/procedures/': typeof AuthenticatedReferencesProceduresIndexRoute
  '/_authenticated/patients/$patientId/visits/$visitId': typeof AuthenticatedPatientsPatientIdVisitsVisitIdRoute
  '/_authenticated/patients/$patientId/visits/': typeof AuthenticatedPatientsPatientIdVisitsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/patients/$patientId'
    | '/manufacturers/'
    | '/patients/'
    | '/products/'
    | '/queues/'
    | '/roles/'
    | '/users/'
    | '/patients/$patientId/'
    | '/references/conditions/'
    | '/references/procedures/'
    | '/patients/$patientId/visits/$visitId'
    | '/patients/$patientId/visits/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/manufacturers'
    | '/patients'
    | '/products'
    | '/queues'
    | '/roles'
    | '/users'
    | '/patients/$patientId'
    | '/references/conditions'
    | '/references/procedures'
    | '/patients/$patientId/visits/$visitId'
    | '/patients/$patientId/visits'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/_authenticated/'
    | '/_authenticated/patients/$patientId'
    | '/_authenticated/manufacturers/'
    | '/_authenticated/patients/'
    | '/_authenticated/products/'
    | '/_authenticated/queues/'
    | '/_authenticated/roles/'
    | '/_authenticated/users/'
    | '/_authenticated/patients/$patientId/'
    | '/_authenticated/references/conditions/'
    | '/_authenticated/references/procedures/'
    | '/_authenticated/patients/$patientId/visits/$visitId'
    | '/_authenticated/patients/$patientId/visits/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/manufacturers/': {
      id: '/_authenticated/manufacturers/'
      path: '/manufacturers'
      fullPath: '/manufacturers/'
      preLoaderRoute: typeof AuthenticatedManufacturersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/': {
      id: '/_authenticated/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof AuthenticatedPatientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId': {
      id: '/_authenticated/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/products/': {
      id: '/_authenticated/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AuthenticatedProductsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/queues/': {
      id: '/_authenticated/queues/'
      path: '/queues'
      fullPath: '/queues/'
      preLoaderRoute: typeof AuthenticatedQueuesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/roles/': {
      id: '/_authenticated/roles/'
      path: '/roles'
      fullPath: '/roles/'
      preLoaderRoute: typeof AuthenticatedRolesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId/': {
      id: '/_authenticated/patients/$patientId/'
      path: '/'
      fullPath: '/patients/$patientId/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/references/conditions/': {
      id: '/_authenticated/references/conditions/'
      path: '/references/conditions'
      fullPath: '/references/conditions/'
      preLoaderRoute: typeof AuthenticatedReferencesConditionsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/references/procedures/': {
      id: '/_authenticated/references/procedures/'
      path: '/references/procedures'
      fullPath: '/references/procedures/'
      preLoaderRoute: typeof AuthenticatedReferencesProceduresIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/patients/$patientId/visits/': {
      id: '/_authenticated/patients/$patientId/visits/'
      path: '/visits'
      fullPath: '/patients/$patientId/visits/'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdVisitsIndexRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
    '/_authenticated/patients/$patientId/visits/$visitId': {
      id: '/_authenticated/patients/$patientId/visits/$visitId'
      path: '/visits/$visitId'
      fullPath: '/patients/$patientId/visits/$visitId'
      preLoaderRoute: typeof AuthenticatedPatientsPatientIdVisitsVisitIdRouteImport
      parentRoute: typeof AuthenticatedPatientsPatientIdRoute
    }
  }
}

interface AuthenticatedPatientsPatientIdRouteChildren {
  AuthenticatedPatientsPatientIdIndexRoute: typeof AuthenticatedPatientsPatientIdIndexRoute
  AuthenticatedPatientsPatientIdVisitsVisitIdRoute: typeof AuthenticatedPatientsPatientIdVisitsVisitIdRoute
  AuthenticatedPatientsPatientIdVisitsIndexRoute: typeof AuthenticatedPatientsPatientIdVisitsIndexRoute
}

const AuthenticatedPatientsPatientIdRouteChildren: AuthenticatedPatientsPatientIdRouteChildren =
  {
    AuthenticatedPatientsPatientIdIndexRoute:
      AuthenticatedPatientsPatientIdIndexRoute,
    AuthenticatedPatientsPatientIdVisitsVisitIdRoute:
      AuthenticatedPatientsPatientIdVisitsVisitIdRoute,
    AuthenticatedPatientsPatientIdVisitsIndexRoute:
      AuthenticatedPatientsPatientIdVisitsIndexRoute,
  }

const AuthenticatedPatientsPatientIdRouteWithChildren =
  AuthenticatedPatientsPatientIdRoute._addFileChildren(
    AuthenticatedPatientsPatientIdRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedPatientsPatientIdRoute: typeof AuthenticatedPatientsPatientIdRouteWithChildren
  AuthenticatedManufacturersIndexRoute: typeof AuthenticatedManufacturersIndexRoute
  AuthenticatedPatientsIndexRoute: typeof AuthenticatedPatientsIndexRoute
  AuthenticatedProductsIndexRoute: typeof AuthenticatedProductsIndexRoute
  AuthenticatedQueuesIndexRoute: typeof AuthenticatedQueuesIndexRoute
  AuthenticatedRolesIndexRoute: typeof AuthenticatedRolesIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedReferencesConditionsIndexRoute: typeof AuthenticatedReferencesConditionsIndexRoute
  AuthenticatedReferencesProceduresIndexRoute: typeof AuthenticatedReferencesProceduresIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedPatientsPatientIdRoute:
    AuthenticatedPatientsPatientIdRouteWithChildren,
  AuthenticatedManufacturersIndexRoute: AuthenticatedManufacturersIndexRoute,
  AuthenticatedPatientsIndexRoute: AuthenticatedPatientsIndexRoute,
  AuthenticatedProductsIndexRoute: AuthenticatedProductsIndexRoute,
  AuthenticatedQueuesIndexRoute: AuthenticatedQueuesIndexRoute,
  AuthenticatedRolesIndexRoute: AuthenticatedRolesIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedReferencesConditionsIndexRoute:
    AuthenticatedReferencesConditionsIndexRoute,
  AuthenticatedReferencesProceduresIndexRoute:
    AuthenticatedReferencesProceduresIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
